import type { Metadata } from "next";
import {
  Be_Vietnam_Pro,
  Plus_Jakarta_Sans,
  Bungee_Outline
} from "next/font/google";


import "./globals.css";

const beVietnamPro = Be_Vietnam_Pro({
  variable: "--font-be-vietnam-pro",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const bungee = Bungee_Outline({
  variable: "--font-bungee",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${beVietnamPro.variable} ${plusJakartaSans.variable} ${bungee.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
